run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - unconvert
    - misspell
    - gocyclo
    - gofmt
    - goimports

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  gocyclo:
    min-complexity: 15
  govet:
    shadow: true